sonar.organization=resolum
sonar.projectKey=resolum_alivia-landing-page

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.astro/**,**/*.spec.ts,**/*.test.ts
